version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DC_TOKEN=${DC_TOKEN}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PW}
    restart: unless-stopped
    
  db:
    hostname: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PW}
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local